<?php
/**
 * $Id: xoops_version.php
 * Module: PD-Downloads
 * Version: v1.2
 * Release Date: 21. Dec 2005
 * Author: Power-Dreams Team
 * Licence: GNU
 */

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;
if( ! preg_match( '/^(\D+)(\d*)$/' , $mydirname , $regs ) ) echo ( "invalid dirname: " . htmlspecialchars( $mydirname ) ) ;
$mydirnumber = $regs[2] === '' ? '' : intval( $regs[2] ) ;

$modversion['name'] = _MI_PDD_NAME.$mydirnumber;
$modversion['version'] = 1.2;
$modversion['releasedate'] = "21. December 2005";
$modversion['status'] = "Stable";
$modversion['description'] = _MI_PDD_DESC;
$modversion['author'] = "Power-Dreams Team";
$modversion['credits'] = "Power-Dreams Team -> www.power-dreams.com";
$modversion['license'] = "GPL see LICENSE";
$modversion['image'] = "images/PDdl_slogo{$mydirnumber}.png";
$modversion['dirname'] = $mydirname;

$modversion['author_website_url'] = "http://www.power-dreams.com";
$modversion['author_website_name'] = "Power-Dreams";
$modversion['author_email'] = "coding@power-dreams.com";

$modversion['warning'] = _MI_PDD_WARNINGTEXT;
$modversion['author_credits'] = _MI_PDD_AUTHOR_CREDITSTEXT;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/PDdownloads{$mydirnumber}.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "PDdownloads{$mydirnumber}_broken";
$modversion['tables'][1] = "PDdownloads{$mydirnumber}_cat";
$modversion['tables'][2] = "PDdownloads{$mydirnumber}_downloads";
$modversion['tables'][3] = "PDdownloads{$mydirnumber}_mod";
$modversion['tables'][4] = "PDdownloads{$mydirnumber}_votedata";
$modversion['tables'][5] = "PDdownloads{$mydirnumber}_indexpage";
$modversion['tables'][7] = "PDdownloads{$mydirnumber}_mimetypes";
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
//update things
$modversion['onUpdate'] = 'include/module.php';
// Blocks
$modversion['blocks'][1]['file'] = "PDdownloads_top.php";
$modversion['blocks'][1]['name'] = _MI_PDD_BNAME1.$mydirnumber;
$modversion['blocks'][1]['description'] = "Shows recently added donwload files";
$modversion['blocks'][1]['show_func'] = "b_PDdownloads_top_show";
$modversion['blocks'][1]['edit_func'] = "b_PDdownloads_top_edit";
$modversion['blocks'][1]['options'] = "published|10|19|{$mydirname}";
$modversion['blocks'][1]['template'] = "PDdownloads{$mydirnumber}_block_new.html";
$modversion['blocks'][1]['can_clone'] = true ; //Block-Cloneable

$modversion['blocks'][2]['file'] = "PDdownloads_top.php";
$modversion['blocks'][2]['name'] = _MI_PDD_BNAME2.$mydirnumber;
$modversion['blocks'][2]['description'] = "Shows most downloaded files";
$modversion['blocks'][2]['show_func'] = "b_PDdownloads_top_show";
$modversion['blocks'][2]['edit_func'] = "b_PDdownloads_top_edit";
$modversion['blocks'][2]['options'] = "hits|10|19|{$mydirname}";
$modversion['blocks'][2]['template'] = "PDdownloads{$mydirnumber}_block_top.html";
$modversion['blocks'][2]['can_clone'] = true ; //Block-Cloneable

// Menu
$modversion['hasMain'] = 1;

global $xoopsModuleConfig, $xoopsUser, $xoopsDLModule;

$modhandler = &xoops_gethandler('module');
$xoopsDLModule = &$modhandler->getByDirname($mydirname);

if (is_object($xoopsDLModule) && $xoopsDLModule->getVar('isactive'))
{
	if ($xoopsUser && isset($xoopsModuleConfig['submitarts']) && array_intersect($xoopsModuleConfig['submitarts'], $xoopsUser->getGroups()))
	$submissions = 1;
	else if (!$xoopsUser && isset($xoopsModuleConfig['anonpost']) && $xoopsModuleConfig['anonpost'] == 1)
	$submissions = 1;
}

$i = 0;
if (!empty($submissions))
{
	$i++;
	$modversion['sub'][$i]['name'] = _MI_PDD_SMNAME1;
	$modversion['sub'][$i]['url'] = "submit.php";
}
if ($xoopsUser)
{
	$i++;
	$modversion['sub'][$i]['name'] = _MI_PDD_SMNAME4;
	$modversion['sub'][$i]['url'] = "viewcat.php?uid=".$xoopsUser->getVar('uid')."";
}

$i++;
$modversion['sub'][$i]['name'] = _MI_PDD_SMNAME2;
$modversion['sub'][$i]['url'] = "topten.php?list=hit";
$i++;
$modversion['sub'][$i]['name'] = _MI_PDD_SMNAME3;
$modversion['sub'][$i]['url'] = "topten.php?list=rate";
unset($i);
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "PDdownloads{$mydirnumber}_search";
// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'lid';
$modversion['comments']['pageName'] = 'singlefile.php';
$modversion['comments']['extraParams'] = array('cid');
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'PDdownloads_com_approve';
$modversion['comments']['callback']['update'] = 'PDdownloads_com_update';
// Templates
$modversion['templates'][1]['file'] = "PDdownloads{$mydirnumber}_brokenfile.html";
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = "PDdownloads{$mydirnumber}_download.html";
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = "PDdownloads{$mydirnumber}_index.html";
$modversion['templates'][3]['description'] = '';
$modversion['templates'][5]['file'] = "PDdownloads{$mydirnumber}_ratefile.html";
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = "PDdownloads{$mydirnumber}_singlefile.html";
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = "PDdownloads{$mydirnumber}_submit.html";
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = "PDdownloads{$mydirnumber}_topten.html";
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = "PDdownloads{$mydirnumber}_viewcat.html";
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = "PDdownloads{$mydirnumber}_newlistindex.html";
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = "PDdownloads{$mydirnumber}_viewlist.html";
$modversion['templates'][11]['description'] = '';

//Module config setting
$modversion['config'][1]['name'] = 'popular';
$modversion['config'][1]['title'] = '_MI_PDD_POPULAR';
$modversion['config'][1]['description'] = '_MI_PDD_POPULARDSC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 100;
$modversion['config'][1]['options'] = array('5' => 5, '10' => 10, '50' => 50, '100' => 100, '200' => 200, '500' => 500, '1000' => 1000);

$modversion['config'][2]['name'] = 'displayicons';
$modversion['config'][2]['title'] = '_MI_PDD_ICONDISPLAY';
$modversion['config'][2]['description'] = '_MI_PDD_DISPLAYICONDSC';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;
$modversion['config'][2]['options'] = array('_MI_PDD_DISPLAYICON1' => 1, '_MI_PDD_DISPLAYICON2' => 2, '_MI_PDD_DISPLAYICON3' => 3);

$modversion['config'][41]['name'] = 'daysnew';
$modversion['config'][41]['title'] = '_MI_PDD_DAYSNEW';
$modversion['config'][41]['description'] = '_MI_PDD_DAYSNEWDSC';
$modversion['config'][41]['formtype'] = 'textbox';
$modversion['config'][41]['valuetype'] = 'int';
$modversion['config'][41]['default'] = 10;

$modversion['config'][42]['name'] = 'daysupdated';
$modversion['config'][42]['title'] = '_MI_PDD_DAYSUPDATED';
$modversion['config'][42]['description'] = '_MI_PDD_DAYSUPDATEDDSC';
$modversion['config'][42]['formtype'] = 'textbox';
$modversion['config'][42]['valuetype'] = 'int';
$modversion['config'][42]['default'] = 10;

$modversion['config'][44]['name'] = 'showdlonindex';
$modversion['config'][44]['title'] = '_MI_PDD_SHOWDLONINDEX';
$modversion['config'][44]['description'] = '_MI_PDD_SHOWDLONINDEXDSC';
$modversion['config'][44]['formtype'] = 'yesno';
$modversion['config'][44]['valuetype'] = 'int';
$modversion['config'][44]['default'] = 0;

$modversion['config'][3]['name'] = 'perpage';
$modversion['config'][3]['title'] = '_MI_PDD_PERPAGE';
$modversion['config'][3]['description'] = '_MI_PDD_PERPAGEDSC';
$modversion['config'][3]['formtype'] = 'select';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 10;
$modversion['config'][3]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);

$modversion['config'][35]['name'] = 'admin_perpage';
$modversion['config'][35]['title'] = '_MI_PDD_ADMINPAGE';
$modversion['config'][35]['description'] = '_MI_PDD_AMDMINPAGEDSC';
$modversion['config'][35]['formtype'] = 'select';
$modversion['config'][35]['valuetype'] = 'int';
$modversion['config'][35]['default'] = 10;
$modversion['config'][35]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50);

$qa = ' (A)';
$qd = ' (D)';

$modversion['config'][39]['name'] = 'filexorder';
$modversion['config'][39]['title'] = '_MI_PDD_ARTICLESSORT';
$modversion['config'][39]['description'] = '_MI_PDD_ARTICLESSORTDSC';
$modversion['config'][39]['formtype'] = 'select';
$modversion['config'][39]['valuetype'] = 'text';
$modversion['config'][39]['default'] = 'title ASC';
$modversion['config'][39]['options'] = array(_MI_PDD_TITLE . $qa => 'title ASC',
_MI_PDD_TITLE . $qd => 'title DESC',
_MI_PDD_SUBMITTED2 . $qa => 'published ASC' ,
_MI_PDD_SUBMITTED2 . $qd => 'published DESC',
_MI_PDD_RATING . $qa => 'rating ASC',
_MI_PDD_RATING . $qd => 'rating DESC',
_MI_PDD_POPULARITY . $qa => 'hits ASC',
_MI_PDD_POPULARITY . $qd => 'hits DESC',
_MI_PDD_WEIGHT => 'weight');

$modversion['config'][43]['name'] = 'dividecategory';
$modversion['config'][43]['title'] = '_MI_PDD_DIVIDECATEGORY';
$modversion['config'][43]['description'] = '_MI_PDD_DIVCATDSC';
$modversion['config'][43]['formtype'] = 'select';
$modversion['config'][43]['valuetype'] = 'int';
$modversion['config'][43]['default'] = 2;
$modversion['config'][43]['options'] = array('1' => 1, '2' => 2, '3' => 3, '4' => 4);

$modversion['config'][33]['name'] = 'dividesubcat';
$modversion['config'][33]['title'] = '_MI_PDD_DIVSUBCAT';
$modversion['config'][33]['description'] = '_MI_PDD_DIVSUBCATDSC';
$modversion['config'][33]['formtype'] = 'select';
$modversion['config'][33]['valuetype'] = 'int';
$modversion['config'][33]['default'] = 2;
$modversion['config'][33]['options'] = array('1' => 1, '2' => 2, '3' => 3, '4' => 4);

$modversion['config'][32]['name'] = 'subcats';
$modversion['config'][32]['title'] = '_MI_PDD_SUBCATS';
$modversion['config'][32]['description'] = '_MI_PDD_SUBCATSDSC';
$modversion['config'][32]['formtype'] = 'yesno';
$modversion['config'][32]['valuetype'] = 'int';
$modversion['config'][32]['default'] = 0;

$modversion['config'][6]['name'] = 'screenshot';
$modversion['config'][6]['title'] = '_MI_PDD_USESHOTS';
$modversion['config'][6]['description'] = '_MI_PDD_USESHOTSDSC';
$modversion['config'][6]['formtype'] = 'yesno';
$modversion['config'][6]['valuetype'] = 'int';
$modversion['config'][6]['default'] = 0;

$modversion['config'][21]['name'] = 'usethumbs';
$modversion['config'][21]['title'] = '_MI_PDD_USETHUMBS';
$modversion['config'][21]['description'] = '_MI_PDD_USETHUMBSDSC';
$modversion['config'][21]['formtype'] = 'yesno';
$modversion['config'][21]['valuetype'] = 'int';
$modversion['config'][21]['default'] = 0;

$modversion['config'][36]['name'] = 'updatethumbs';
$modversion['config'][36]['title'] = '_MI_PDD_IMGUPDATE';
$modversion['config'][36]['description'] = '_MI_PDD_IMGUPDATEDSC';
$modversion['config'][36]['formtype'] = 'yesno';
$modversion['config'][36]['valuetype'] = 'int';
$modversion['config'][36]['default'] = 1;

$modversion['config'][37]['name'] = 'imagequality';
$modversion['config'][37]['title'] = '_MI_PDD_QUALITY';
$modversion['config'][37]['description'] = '_MI_PDD_QUALITYDSC';
$modversion['config'][37]['formtype'] = 'textbox';
$modversion['config'][37]['valuetype'] = 'int';
$modversion['config'][37]['default'] = 100;

$modversion['config'][38]['name'] = 'keepaspect';
$modversion['config'][38]['title'] = '_MI_PDD_KEEPASPECT';
$modversion['config'][38]['description'] = '_MI_PDD_KEEPASPECTDSC';
$modversion['config'][38]['formtype'] = 'yesno';
$modversion['config'][38]['valuetype'] = 'int';
$modversion['config'][38]['default'] = 0;

$modversion['config'][7]['name'] = 'shotwidth';
$modversion['config'][7]['title'] = '_MI_PDD_SHOTWIDTH';
$modversion['config'][7]['description'] = '_MI_PDD_SHOTWIDTHDSC';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 140;

$modversion['config'][20]['name'] = 'shotheight';
$modversion['config'][20]['title'] = '_MI_PDD_SHOTHEIGHT';
$modversion['config'][20]['description'] = '_MI_PDD_SHOTHEIGHTDSC';
$modversion['config'][20]['formtype'] = 'textbox';
$modversion['config'][20]['valuetype'] = 'int';
$modversion['config'][20]['default'] = 79;

$modversion['config'][8]['name'] = 'check_host';
$modversion['config'][8]['title'] = '_MI_PDD_CHECKHOST';
$modversion['config'][8]['description'] = '';
$modversion['config'][8]['formtype'] = 'yesno';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 0;

$xoops_url = parse_url(XOOPS_URL);
$modversion['config'][9]['name'] = 'referers';
$modversion['config'][9]['title'] = '_MI_PDD_REFERERS';
$modversion['config'][9]['description'] = '_MI_PDD_REFERERSDSC';
$modversion['config'][9]['formtype'] = 'textarea';
$modversion['config'][9]['valuetype'] = 'array';
$modversion['config'][9]['default'] = array($xoops_url['host']);

$modversion['config'][34]['name'] = 'submitarts';
$modversion['config'][34]['title'] = '_MI_PDD_SUBMITART';
$modversion['config'][34]['description'] = '_MI_PDD_SUBMITARTDSC';
$modversion['config'][34]['formtype'] = 'group_multi';
$modversion['config'][34]['valuetype'] = 'array';
$modversion['config'][34]['default'] = '1';

$modversion['config'][4]['name'] = 'anonpost';
$modversion['config'][4]['title'] = '_MI_PDD_ANONPOST';
$modversion['config'][4]['description'] = '_MI_PDD_ANONPOSTDSC';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][5]['name'] = 'autoapprove';
$modversion['config'][5]['title'] = '_MI_PDD_AUTOAPPROVE';
$modversion['config'][5]['description'] = '_MI_PDD_AUTOAPPROVEDSC';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 0;

$modversion['config'][45]['name'] = 'autoapproveforall';
$modversion['config'][45]['title'] = '_MI_PDD_AUTOAPPROVEFORALL';
$modversion['config'][45]['description'] = '_MI_PDD_AUTOAPPROVEFORALLDSC';
$modversion['config'][45]['formtype'] = 'yesno';
$modversion['config'][45]['valuetype'] = 'int';
$modversion['config'][45]['default'] = 0;

$modversion['config'][16]['name'] = 'useruploads';
$modversion['config'][16]['title'] = '_MI_PDD_ALLOWUPLOADS';
$modversion['config'][16]['description'] = '_MI_PDD_ALLOWUPLOADSDSC';
$modversion['config'][16]['formtype'] = 'yesno';
$modversion['config'][16]['valuetype'] = 'int';
$modversion['config'][16]['default'] = 0;

$modversion['config'][10]['name'] = 'maxfilesize';
$modversion['config'][10]['title'] = '_MI_PDD_MAXFILESIZE';
$modversion['config'][10]['description'] = '_MI_PDD_MAXFILESIZEDSC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 200000;

$modversion['config'][11]['name'] = 'maximgwidth';
$modversion['config'][11]['title'] = '_MI_PDD_IMGWIDTH';
$modversion['config'][11]['description'] = '_MI_PDD_IMGWIDTHDSC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 600;

$modversion['config'][12]['name'] = 'maximgheight';
$modversion['config'][12]['title'] = '_MI_PDD_IMGHEIGHT';
$modversion['config'][12]['description'] = '_MI_PDD_IMGHEIGHTDSC';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 600;

$modversion['config'][13]['name'] = 'uploaddir';
$modversion['config'][13]['title'] = '_MI_PDD_UPLOADDIR';
$modversion['config'][13]['description'] = '_MI_PDD_UPLOADDIRDSC';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'text';
$modversion['config'][13]['default'] = "uploads/$mydirname";

$modversion['config'][19]['name'] = 'mainimagedir';
$modversion['config'][19]['title'] = '_MI_PDD_MAINIMGDIR';
$modversion['config'][19]['description'] = '_MI_PDD_MAINIMGDIRDSC';
$modversion['config'][19]['formtype'] = 'textbox';
$modversion['config'][19]['valuetype'] = 'text';
$modversion['config'][19]['default'] = "modules/$mydirname/images";

$modversion['config'][17]['name'] = 'screenshots';
$modversion['config'][17]['title'] = '_MI_PDD_SCREENSHOTS';
$modversion['config'][17]['description'] = '_MI_PDD_SCREENSHOTSDSC';
$modversion['config'][17]['formtype'] = 'textbox';
$modversion['config'][17]['valuetype'] = 'text';
$modversion['config'][17]['default'] = "modules/$mydirname/images/screenshots";

$modversion['config'][18]['name'] = 'catimage';
$modversion['config'][18]['title'] = '_MI_PDD_CATEGORYIMG';
$modversion['config'][18]['description'] = '_MI_PDD_CATEGORYIMGDSC';
$modversion['config'][18]['formtype'] = 'textbox';
$modversion['config'][18]['valuetype'] = 'text';
$modversion['config'][18]['default'] = "modules/$mydirname/images/category";

$modversion['config'][26]['name'] = 'platform';
$modversion['config'][26]['title'] = '_MI_PDD_PLATFORM';
$modversion['config'][26]['description'] = '_MI_PDD_PLATFORMDSC';
$modversion['config'][26]['formtype'] = 'textarea';
$modversion['config'][26]['valuetype'] = 'array';
$modversion['config'][26]['default'] = 'None|Windows|Unix|Mac|Xoops 1.3|Xoops 2.0|Xoops 1.0|Xoops 2.0.6|Xoops 2.0.7|Other';

$modversion['config'][23]['name'] = 'dateformat';
$modversion['config'][23]['title'] = '_MI_PDD_DATEFORMAT';
$modversion['config'][23]['description'] = '_MI_PDD_DATEFORMATDSC';
$modversion['config'][23]['formtype'] = 'textbox';
$modversion['config'][23]['valuetype'] = 'text';
$modversion['config'][23]['default'] = 'D, d-M-Y';

$modversion['config'][24]['name'] = 'showdisclaimer';
$modversion['config'][24]['title'] = '_MI_PDD_SHOWDISCLAIMER';
$modversion['config'][24]['description'] = '_MI_PDD_SHOWDISCLAIMERDSC';
$modversion['config'][24]['formtype'] = 'yesno';
$modversion['config'][24]['valuetype'] = 'int';
$modversion['config'][24]['default'] = 0;

$modversion['config'][25]['name'] = 'disclaimer';
$modversion['config'][25]['title'] = '_MI_PDD_DISCLAIMER';
$modversion['config'][25]['description'] = '_MI_PDD_DISCLAIMERDSC';
$modversion['config'][25]['formtype'] = 'textarea';
$modversion['config'][25]['valuetype'] = 'text';
$modversion['config'][25]['default'] = 'We have the right, but not the obligation to monitor and review submissions submitted by users, in the forums. We shall not be responsible for any of the content of these messages. We further reserve the right, to delete, move or edit submissions that the we, in its exclusive discretion, deems abusive, defamatory, obscene or in violation of any Copyright or Trademark laws or otherwise objectionable.';

$modversion['config'][29]['name'] = 'showDowndisclaimer';
$modversion['config'][29]['title'] = '_MI_PDD_SHOWDOWNDISCL';
$modversion['config'][29]['description'] = '_MI_PDD_SHOWDOWNDISCLDSC';
$modversion['config'][29]['formtype'] = 'yesno';
$modversion['config'][29]['valuetype'] = 'int';
$modversion['config'][29]['default'] = 0;

$modversion['config'][30]['name'] = 'downdisclaimer';
$modversion['config'][30]['title'] = '_MI_PDD_DOWNDISCLAIMER';
$modversion['config'][30]['description'] = '_MI_PDD_DOWNDISCLAIMERDSC';
$modversion['config'][30]['formtype'] = 'textarea';
$modversion['config'][30]['valuetype'] = 'text';
$modversion['config'][30]['default'] = 'The file downloads on this site are provided as is without warranty either expressed or implied. Downloaded files should be checked for possible virus infection using the most up-to-date detection and security packages. If you have a question concerning a particular piece of software, feel free to contact the developer. We refuse liability for any damage or loss resulting from the use or misuse of any software offered from this site for downloading. If you have any doubt at all about the safety and operation of software made available to you on this site, do not download it.<br /><br />Contact us if you have questions concerning this disclaimer.';

$modversion['config'][40]['name'] = 'copyright';
$modversion['config'][40]['title'] = '_MI_PDD_COPYRIGHT';
$modversion['config'][40]['description'] = '_MI_PDD_COPYRIGHTDSC';
$modversion['config'][40]['formtype'] = 'yesno';
$modversion['config'][40]['valuetype'] = 'int';
$modversion['config'][40]['default'] = 1;

$modversion['config'][46]['name'] = 'allowrss';
$modversion['config'][46]['title'] = '_MI_PDD_RSS';
$modversion['config'][46]['description'] = '_MI_PDD_RSSDSC';
$modversion['config'][46]['formtype'] = 'yesno';
$modversion['config'][46]['valuetype'] = 'int';
$modversion['config'][46]['default'] = 0;


// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = "PDdownloads{$mydirnumber}_notify_iteminfo";

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_PDD_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_PDD_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php', 'viewcat.php', 'singlefile.php');

$modversion['notification']['category'][2]['name'] = 'category';
$modversion['notification']['category'][2]['title'] = _MI_PDD_CATEGORY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_PDD_CATEGORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('viewcat.php', 'singlefile.php');
$modversion['notification']['category'][2]['item_name'] = 'cid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['category'][3]['name'] = 'file';
$modversion['notification']['category'][3]['title'] = _MI_PDD_FILE_NOTIFY;
$modversion['notification']['category'][3]['description'] = _MI_PDD_FILE_NOTIFYDSC;
$modversion['notification']['category'][3]['subscribe_from'] = 'singlefile.php';
$modversion['notification']['category'][3]['item_name'] = 'lid';
$modversion['notification']['category'][3]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_category';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_PDD_GLOBAL_NEWCATEGORY_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_PDD_GLOBAL_NEWCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_PDD_GLOBAL_NEWCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcategory_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_PDD_GLOBAL_NEWCATEGORY_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'file_modify';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 1;
$modversion['notification']['event'][2]['title'] = _MI_PDD_GLOBAL_FILEMODIFY_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_PDD_GLOBAL_FILEMODIFY_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_PDD_GLOBAL_FILEMODIFY_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_filemodify_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_PDD_GLOBAL_FILEMODIFY_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'file_broken';
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['admin_only'] = 1;
$modversion['notification']['event'][3]['title'] = _MI_PDD_GLOBAL_FILEBROKEN_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_PDD_GLOBAL_FILEBROKEN_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_PDD_GLOBAL_FILEBROKEN_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_filebroken_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_PDD_GLOBAL_FILEBROKEN_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'file_submit';
$modversion['notification']['event'][4]['category'] = 'global';
$modversion['notification']['event'][4]['admin_only'] = 1;
$modversion['notification']['event'][4]['title'] = _MI_PDD_GLOBAL_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_PDD_GLOBAL_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_PDD_GLOBAL_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'global_filesubmit_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_PDD_GLOBAL_FILESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][5]['name'] = 'new_file';
$modversion['notification']['event'][5]['category'] = 'global';
$modversion['notification']['event'][5]['title'] = _MI_PDD_GLOBAL_NEPDILE_NOTIFY;
$modversion['notification']['event'][5]['caption'] = _MI_PDD_GLOBAL_NEPDILE_NOTIFYCAP;
$modversion['notification']['event'][5]['description'] = _MI_PDD_GLOBAL_NEPDILE_NOTIFYDSC;
$modversion['notification']['event'][5]['mail_template'] = 'global_newfile_notify';
$modversion['notification']['event'][5]['mail_subject'] = _MI_PDD_GLOBAL_NEPDILE_NOTIFYSBJ;

$modversion['notification']['event'][6]['name'] = 'file_submit';
$modversion['notification']['event'][6]['category'] = 'category';
$modversion['notification']['event'][6]['admin_only'] = 1;
$modversion['notification']['event'][6]['title'] = _MI_PDD_CATEGORY_FILESUBMIT_NOTIFY;
$modversion['notification']['event'][6]['caption'] = _MI_PDD_CATEGORY_FILESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][6]['description'] = _MI_PDD_CATEGORY_FILESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][6]['mail_template'] = 'category_filesubmit_notify';
$modversion['notification']['event'][6]['mail_subject'] = _MI_PDD_CATEGORY_FILESUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][7]['name'] = 'new_file';
$modversion['notification']['event'][7]['category'] = 'category';
$modversion['notification']['event'][7]['title'] = _MI_PDD_CATEGORY_NEPDILE_NOTIFY;
$modversion['notification']['event'][7]['caption'] = _MI_PDD_CATEGORY_NEPDILE_NOTIFYCAP;
$modversion['notification']['event'][7]['description'] = _MI_PDD_CATEGORY_NEPDILE_NOTIFYDSC;
$modversion['notification']['event'][7]['mail_template'] = 'category_newfile_notify';
$modversion['notification']['event'][7]['mail_subject'] = _MI_PDD_CATEGORY_NEPDILE_NOTIFYSBJ;

$modversion['notification']['event'][8]['name'] = 'approve';
$modversion['notification']['event'][8]['category'] = 'file';
$modversion['notification']['event'][8]['invisible'] = 1;
$modversion['notification']['event'][8]['title'] = _MI_PDD_FILE_APPROVE_NOTIFY;
$modversion['notification']['event'][8]['caption'] = _MI_PDD_FILE_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][8]['description'] = _MI_PDD_FILE_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][8]['mail_template'] = 'file_approve_notify';
$modversion['notification']['event'][8]['mail_subject'] = _MI_PDD_FILE_APPROVE_NOTIFYSBJ;

// On Update
/*if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}*/
?>